import { ArrowRight, BarChart3, Code2, Globe2, Menu, Search, Send, Sparkles } from 'lucide-react'
import { CSSProperties, FormEvent, useEffect, useRef, useState } from 'react'

const services = [{ icon: Globe2, title: 'Web experiences', text: 'Distinctive websites built to turn attention into action.' }, { icon: Search, title: 'SEO & search', text: 'Technical SEO and content systems that get you found.' }, { icon: BarChart3, title: 'Digital marketing', text: 'Campaigns and analytics that make growth measurable.' }, { icon: Code2, title: 'Tech development', text: 'Practical software and integrations made for real work.' }]
const page = location.pathname.includes('services') ? 'services' : location.pathname.includes('about') ? 'about' : location.pathname.includes('contact') ? 'contact' : 'home'
const SPOTLIGHT_R = 260
function CursorReveal(){
  const canvas = useRef<HTMLCanvasElement>(null), mouse = useRef({x:-999,y:-999}), smooth = useRef({x:-999,y:-999}), raf = useRef(0)
  const [mask,setMask] = useState('none')
  useEffect(()=>{const move=(e:MouseEvent)=>{mouse.current={x:e.clientX,y:e.clientY}};const paint=()=>{const c=canvas.current;if(!c)return;c.width=innerWidth;c.height=innerHeight;const x=smooth.current.x,y=smooth.current.y,g=c.getContext('2d');if(!g)return;g.clearRect(0,0,c.width,c.height);const r=g.createRadialGradient(x,y,0,x,y,SPOTLIGHT_R);[[0,1],[.4,1],[.6,.75],[.75,.4],[.88,.12],[1,0]].forEach(([stop,alpha])=>r.addColorStop(stop,`rgba(255,255,255,${alpha})`));g.fillStyle=r;g.beginPath();g.arc(x,y,SPOTLIGHT_R,0,Math.PI*2);g.fill();setMask(c.toDataURL())};const loop=()=>{smooth.current.x+=(mouse.current.x-smooth.current.x)*.1;smooth.current.y+=(mouse.current.y-smooth.current.y)*.1;paint();raf.current=requestAnimationFrame(loop)};addEventListener('mousemove',move);raf.current=requestAnimationFrame(loop);return()=>{removeEventListener('mousemove',move);cancelAnimationFrame(raf.current)}},[])
  const style:CSSProperties={backgroundImage:'url(/BG_IMAGE_2.jpg)',maskImage:`url(${mask})`,WebkitMaskImage:`url(${mask})`,maskSize:'100% 100%',WebkitMaskSize:'100% 100%'}
  return <><div className="hero-base"/><canvas ref={canvas} style={{display:'none'}}/><div className="hero-reveal" style={style}/></>
}
function Header() { const [open, setOpen] = useState(false); return <header><a className="brand" href="/"><b>y</b>ezhuththu<span>.</span></a><nav>{[['Services','/services.html'],['Our story','/about.html'],['Contact','/contact.html']].map(([n,l])=><a href={l} key={l}>{n}</a>)}</nav><a className="head-cta" href="/contact.html">Start a project <ArrowRight size={15}/></a><button className="menu" onClick={()=>setOpen(!open)}><Menu/></button>{open&&<div className="mobile">{[['Services','/services.html'],['Our story','/about.html'],['Contact','/contact.html']].map(([n,l])=><a href={l} key={l}>{n}</a>)}</div>}</header> }
function Cards(){return <div className="cards">{services.map(({icon:Icon,title,text},i)=><article className="card" key={title} style={{animationDelay:`${i*.1}s`}}><Icon/><small>YEZHUTHTHU / 0{i+1}</small><h3>{title}</h3><p>{text}</p><a href="/contact.html">Explore <ArrowRight size={16}/></a></article>)}</div>}
function Form(){const [status,setStatus]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus('Sending…');const f=new FormData(e.currentTarget);try{const r=await fetch('https://agency-backend-t8oq.onrender.com/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientname:f.get('name'),email:f.get('email'),serviceType:f.get('service'),projectDetails:f.get('details'),estimatedBudget:Number(f.get('budget'))})});if(!r.ok)throw Error();e.currentTarget.reset();setStatus('Thank you — your enquiry is on its way.')}catch{setStatus('Unable to send right now. Please try again.')}}return <form onSubmit={submit}><div className="form-grid"><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input type="email" name="email" required placeholder="you@company.com"/></label><label>Service<select name="service"><option>Website design & development</option><option>SEO & search strategy</option><option>Digital marketing</option><option>Tech development</option></select></label><label>Budget<select name="budget"><option value="100000">Under ₹1 lakh</option><option value="300000">₹1–3 lakh</option><option value="700000">₹3 lakh+</option></select></label></div><label>Project details<textarea name="details" required placeholder="What are you hoping to build?"/></label><button className="primary">Send enquiry <Send size={17}/></button>{status&&<p className="status">{status}</p>}</form>}
function Home(){return <><section className="hero"><CursorReveal/><i className="orb a"/><div className="hero-content"><p className="eyebrow"><Sparkles size={14}/> DIGITAL STUDIO · INDIA & BEYOND</p><h1>Make your next<br/><em>move</em> matter.</h1><p className="lead">Yezhuththu builds sharp, high-performing digital homes for businesses ready to be remembered.</p><a className="primary" href="/contact.html">Build with us <ArrowRight size={17}/></a></div><p className="scroll">MOVE YOUR CURSOR TO EXPLORE ↓</p></section><section className="intro"><p className="eyebrow">DESIGNED FOR MOMENTUM</p><h2>Beautiful is the beginning.<br/><em>Useful</em> is the standard.</h2><p>We connect brand thinking, technology, and marketing into one clear system—so your business works harder online.</p></section><section className="content"><p className="eyebrow">CAPABILITIES</p><h2>Everything a growing<br/>digital presence needs.</h2><Cards/></section><div className="ticker">WEB DESIGN ✦ SEO ✦ DIGITAL GROWTH ✦ DEVELOPMENT ✦ WEB DESIGN ✦ SEO ✦</div><section className="closing"><p className="eyebrow">HAVE A BRIEF?</p><h2>Let’s make the internet<br/><em>work for you.</em></h2><a className="primary" href="/contact.html">Start a conversation <ArrowRight size={17}/></a></section></>}
function Inner(){const title=page==='services'?<>Digital work that<br/><em>moves business.</em></>:page==='about'?<>Curious minds.<br/><em>Measured moves.</em></>:<>Let’s start with<br/>a <em>good question.</em></>;return <main className="inner"><p className="eyebrow">{page==='contact'?'TELL US WHAT’S NEXT':page==='about'?'THE YEZHUTHTHU WAY':'HOW WE HELP'}</p><h1>{title}</h1><p className="lead">{page==='contact'?'Share a few details about your idea. We will return with clear next steps.':page==='about'?'A compact digital studio for ambitious people who care about how their business shows up online.':'From your first click to your next customer, we design the full experience with intention.'}</p>{page==='services'?<Cards/>:page==='contact'?<Form/>:<div className="about-copy">We believe a strong digital presence is not decoration. It is an advantage you can build.</div>}</main>}
export default function App(){return <><Header/>{page==='home'?<Home/>:<Inner/>}<footer><a className="brand" href="/"><b>y</b>ezhuththu<span>.</span></a><p>Websites, marketing, SEO and technology—made with purpose.</p><p>© 2026 Yezhuththu</p></footer></>}
